---
title: "SDS 322E Project: Myocardial Infarction Complications"
author: Kishen Narayan, Kathleen Leever, Yuvraj Uddanti, Diya Sharma, Laura Nylykke,
  Nick Read, Sam Song
date: "2022-10-11"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Project Title
Myocardial Infarction Complications  

## Project Description
Our project goals are to predict complications of Myocardial Infarctions (MI) based on information about the patient at the time of admission and on the third day of the hospital period. 

We explore four specific complications - atrial fibrilation, ventricular tachycardia, relapse of the myocardial infarction, and chronic heart failure. We will analyze these complications through selected input features. Our tentative plan is to classify what type of complication will arise from patient infomartion. 

## Link to Dataset
https://archive.ics.uci.edu/ml/machine-learning-databases/00579/

## Dataset Description
The University of California at Irvine (UCI) maintains multiple datasets used for various ML tasks. The Myocardial Infarction Complications dataset was created by the University of Leicester. The dataset contains different complications related to MI and measures a variety of inputs related to the patient upon admission to the hospital, the ends of the first, second and third days.The various complications include but are not limited to Atrial Fibrilation, Supraventricular Tachycardia, Ventrircular Tachycardia, etc. The input features measured for each patient included but are not limited to age, gender, sex, first-degree AV block in the anamnesis, etc.

For our exploratory analysis we will only look a certain number of the most common complications by selected input features.

# Additional Info & References 
The following paper provided as a base to select for certain complications to study, while we do not employ neural networks, this paper is a reference we considered. The 

https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=480871&tag=1

The following directly links to the University of Leicester, where a descriptive report of the dataset, statistics and dataset is provided.

https://doi.org/10.25392/leicester.data.12045261.v3

# Github Repository
https://github.com/sarvagnyanarayan/myocardial-infarctions.git